AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'modules/**/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/RegexpLiteral:
  # EnforcedStyle: slashes # Doesn't seem to work :'(
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/WordArray:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInArguments:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/CaseEquality:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false
