language: ruby
matrix:
  include:
    - rvm: "1.9.3"
      env: PUPPET_VERSION="3.4.3" # Version installed on Trusty
    - rvm: "1.9.3"
      env: PUPPET_VERSION="~> 3.8.0" # Latest 3.x version
    - rvm: "2.1.8"
      env: PUPPET_VERSION="~> 4.3.0" # Puppetlabs PC1 (latest 4.x version)
env:
  - LIBRARIAN_PUPPET_TMP="$HOME/librarian-puppet"
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet

script: bundle exec rake test
